export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import type { AppProps } from 'next/app';
import Web3Provider from '@/components/Web3Provider';
import '@/styles/globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Web3Provider>{children}</Web3Provider>
      </body>
    </html>
  )
}
